#!/usr/bin/python3
import smtplib
import string
import sys
import getopt

try:
   options,args = getopt.getopt(sys.argv[1:],"ht:s:m:","--help --to= --subject= --message=")
except getopt.GetoptError:
   usage()
for name,value in options:
    if name in ("-h","--help"):
       usage()
    if name in ("-t","--to"):
# accept message user
       TO = value
       TO = TO.split(",")
    if name in ("-s","--title"):
       SUBJECT = value
    if name in ("-m","--message"):
       MESSAGE = value
       MESSAGE = MESSAGE.split('\\n')
       MESSAGE = '\n'.join(MESSAGE)

#smtp HOST
HOST = "your.smtp.host"               
#smtp port
PORT = "587"                              
#FROM mail user
USER = 'user'                         
#FROM mail password
PASSWD = 'password'                    
#FROM EMAIL
FROM = "no-reply@example.com"  

message = """From: %s\nTo: %s\nSubject: %s\n\n%s
    """ % (FROM, ", ".join(TO), SUBJECT, MESSAGE)
smtp = smtplib.SMTP(HOST,PORT)
smtp.ehlo()
smtp.starttls()
smtp.login(USER,PASSWD)
smtp.sendmail(FROM,TO,message)
smtp.close()
